// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sSGOlFmzmdEk-Kn-qYEbm3LaWRHsvSc',
    appId: '1:888780171409:web:2b44541c65ab868eb93730',
    messagingSenderId: '888780171409',
    projectId: 'afri-voyage',
    authDomain: 'afri-voyage.firebaseapp.com',
    storageBucket: 'afri-voyage.firebasestorage.app',
    measurementId: 'G-ZKWVCGWVVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHy1_PnUERMDR4xhxXgl0fFQ4pf5mim0',
    appId: '1:888780171409:android:6acc265e7df2155fb93730',
    messagingSenderId: '888780171409',
    projectId: 'afri-voyage',
    storageBucket: 'afri-voyage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYkDG0eS0o3y0sQHmQH47o0cES8y5PVE',
    appId: '1:888780171409:ios:1ee7ff576ca17feeb93730',
    messagingSenderId: '888780171409',
    projectId: 'afri-voyage',
    storageBucket: 'afri-voyage.firebasestorage.app',
    iosBundleId: 'com.group33.afrivoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuYkDG0eS0o3y0sQHmQH47o0cES8y5PVE',
    appId: '1:888780171409:ios:1ee7ff576ca17feeb93730',
    messagingSenderId: '888780171409',
    projectId: 'afri-voyage',
    storageBucket: 'afri-voyage.firebasestorage.app',
    iosBundleId: 'com.group33.afrivoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8sSGOlFmzmdEk-Kn-qYEbm3LaWRHsvSc',
    appId: '1:888780171409:web:700965965ae47c41b93730',
    messagingSenderId: '888780171409',
    projectId: 'afri-voyage',
    authDomain: 'afri-voyage.firebaseapp.com',
    storageBucket: 'afri-voyage.firebasestorage.app',
    measurementId: 'G-42D15KMZQQ',
  );

}