// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7Zc0RsZxFNQjUq0Eh6_WV-9w1JYAOGg',
    appId: '1:884646714045:web:ed7084975d393841eff5d4',
    messagingSenderId: '884646714045',
    projectId: 'afrivoyage-group33',
    authDomain: 'afrivoyage-group33.firebaseapp.com',
    storageBucket: 'afrivoyage-group33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCNsiHlG937f8SKtsq3TdRFqXM9HKyLA',
    appId: '1:884646714045:android:0077aa175ace83a3eff5d4',
    messagingSenderId: '884646714045',
    projectId: 'afrivoyage-group33',
    storageBucket: 'afrivoyage-group33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDlmpaiyKuVuG6HT1vFDh8P7_lziXzbC0',
    appId: '1:884646714045:ios:81829f8b43e1e09ceff5d4',
    messagingSenderId: '884646714045',
    projectId: 'afrivoyage-group33',
    storageBucket: 'afrivoyage-group33.firebasestorage.app',
    iosBundleId: 'com.group33.afrivoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDlmpaiyKuVuG6HT1vFDh8P7_lziXzbC0',
    appId: '1:884646714045:ios:81829f8b43e1e09ceff5d4',
    messagingSenderId: '884646714045',
    projectId: 'afrivoyage-group33',
    storageBucket: 'afrivoyage-group33.firebasestorage.app',
    iosBundleId: 'com.group33.afrivoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ7Zc0RsZxFNQjUq0Eh6_WV-9w1JYAOGg',
    appId: '1:884646714045:web:aa0c76ef74b4f2d2eff5d4',
    messagingSenderId: '884646714045',
    projectId: 'afrivoyage-group33',
    authDomain: 'afrivoyage-group33.firebaseapp.com',
    storageBucket: 'afrivoyage-group33.firebasestorage.app',
  );
}
